// In-memory database for development without PostgreSQL
// Each array acts as a table. Replace service layer with Prisma when DB is ready.

import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
import type {
  User,
  Patient,
  Department,
  Appointment,
  MedicalRecord,
  ICD10Code,
  RecordDiagnosis,
  LabResult,
  Medication,
  Prescription,
  PrescriptionItem,
  Invoice,
  InvoiceItem,
  Payment,
} from '@hospital-ms/shared';

const now = () => new Date().toISOString();
export const uid = () => crypto.randomUUID();

// ── Counters ──────────────────────────────────────────────────────
let _patientCnt = 11;
let _appointmentCnt = 18;
let _recordCnt = 12;
let _prescriptionCnt = 8;
let _invoiceCnt = 10;

export const nextPatientNo = () =>
  `P-${new Date().getFullYear()}${String(++_patientCnt).padStart(5, '0')}`;
export const nextAppointmentNo = () =>
  `A-${new Date().getFullYear()}${String(++_appointmentCnt).padStart(5, '0')}`;
export const nextRecordNo = () =>
  `R-${new Date().getFullYear()}${String(++_recordCnt).padStart(5, '0')}`;
export const nextPrescriptionNo = () =>
  `RX-${new Date().getFullYear()}${String(++_prescriptionCnt).padStart(5, '0')}`;
export const nextInvoiceNo = () =>
  `INV-${new Date().getFullYear()}${String(++_invoiceCnt).padStart(5, '0')}`;

// ── Departments ───────────────────────────────────────────────────
export const departments: Department[] = [
  { id: 'dept-1', name: '내과', code: 'IM', isActive: true, createdAt: now() },
  { id: 'dept-2', name: '외과', code: 'GS', isActive: true, createdAt: now() },
  { id: 'dept-3', name: '소아과', code: 'PD', isActive: true, createdAt: now() },
  { id: 'dept-4', name: '정형외과', code: 'OS', isActive: true, createdAt: now() },
  { id: 'dept-5', name: '신경과', code: 'NR', isActive: true, createdAt: now() },
  { id: 'dept-6', name: '피부과', code: 'DM', isActive: true, createdAt: now() },
];

// ── Users ─────────────────────────────────────────────────────────
export const users: (User & { password: string })[] = [
  {
    id: 'user-admin-1',
    email: 'admin@hospital.com',
    password: bcrypt.hashSync('admin1234!', 10),
    name: '관리자',
    role: 'ADMIN',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-doctor-1',
    email: 'kim@hospital.com',
    password: bcrypt.hashSync('doctor1234!', 10),
    name: '김민준',
    role: 'DOCTOR',
    licenseNo: 'MD-12345',
    departmentId: 'dept-1',
    phone: '010-1234-5678',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-doctor-2',
    email: 'lee@hospital.com',
    password: bcrypt.hashSync('doctor1234!', 10),
    name: '이서연',
    role: 'DOCTOR',
    licenseNo: 'MD-23456',
    departmentId: 'dept-2',
    phone: '010-2345-6789',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-doctor-3',
    email: 'choi@hospital.com',
    password: bcrypt.hashSync('doctor1234!', 10),
    name: '최신호',
    role: 'DOCTOR',
    licenseNo: 'MD-34567',
    departmentId: 'dept-3',
    phone: '010-3456-7890',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-doctor-4',
    email: 'park@hospital.com',
    password: bcrypt.hashSync('doctor1234!', 10),
    name: '박정우',
    role: 'DOCTOR',
    licenseNo: 'MD-45678',
    departmentId: 'dept-4',
    phone: '010-4567-8901',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-doctor-5',
    email: 'shin@hospital.com',
    password: bcrypt.hashSync('doctor1234!', 10),
    name: '신유진',
    role: 'DOCTOR',
    licenseNo: 'MD-56789',
    departmentId: 'dept-5',
    phone: '010-5678-9012',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-nurse-1',
    email: 'nurse@hospital.com',
    password: bcrypt.hashSync('nurse1234!', 10),
    name: '박지현',
    role: 'NURSE',
    departmentId: 'dept-1',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-recep-1',
    email: 'reception@hospital.com',
    password: bcrypt.hashSync('recep1234!', 10),
    name: '정수아',
    role: 'RECEPTIONIST',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'user-pharm-1',
    email: 'pharm@hospital.com',
    password: bcrypt.hashSync('pharm1234!', 10),
    name: '최약사',
    role: 'PHARMACIST',
    isActive: true,
    createdAt: now(),
    updatedAt: now(),
  },
];

// ── Patients ──────────────────────────────────────────────────────
export const patients: Patient[] = [
  {
    id: 'patient-1',
    patientNo: 'P-202400001',
    name: '홍길동',
    birthDate: '1980-05-15',
    gender: 'MALE',
    phone: '010-1111-2222',
    email: 'hong@example.com',
    address: '서울시 강남구 테헤란로 123',
    insuranceType: 'HEALTH_INSURANCE',
    insuranceNo: 'HI-123456',
    bloodType: 'A+',
    allergies: '페니실린',
    isActive: true,
    firstVisitDate: '2024-01-10',
    lastVisitDate: '2026-05-22',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-2',
    patientNo: 'P-202400002',
    name: '김영희',
    birthDate: '1995-08-22',
    gender: 'FEMALE',
    phone: '010-3333-4444',
    email: 'kim@example.com',
    address: '서울시 서초구 반포대로 56',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'O+',
    isActive: true,
    firstVisitDate: '2024-03-05',
    lastVisitDate: '2026-05-28',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-3',
    patientNo: 'P-202400003',
    name: '박철수',
    birthDate: '1965-12-01',
    gender: 'MALE',
    phone: '010-5555-6666',
    address: '경기도 수원시 팔달구 효원로 100',
    insuranceType: 'MEDICAL_AID_1',
    bloodType: 'B+',
    specialNotes: '고혈압, 당뇨 병력',
    isActive: true,
    firstVisitDate: '2023-06-15',
    lastVisitDate: '2026-05-28',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-4',
    patientNo: 'P-202400004',
    name: '이미래',
    birthDate: '2010-03-14',
    gender: 'FEMALE',
    phone: '010-7777-8888',
    email: 'lee@example.com',
    guardianName: '이진우',
    guardianPhone: '010-9999-0000',
    guardianRelation: '부',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'AB-',
    isActive: true,
    firstVisitDate: '2024-09-10',
    lastVisitDate: '2026-05-10',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-5',
    patientNo: 'P-202400005',
    name: '정도현',
    birthDate: '1975-07-30',
    gender: 'MALE',
    phone: '010-2222-3333',
    address: '서울시 마포구 홍익로 23',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'A-',
    allergies: '아스피린, 설파제',
    isActive: true,
    firstVisitDate: '2024-02-28',
    lastVisitDate: '2026-05-28',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-6',
    patientNo: 'P-202500006',
    name: '최은지',
    birthDate: '1988-11-03',
    gender: 'FEMALE',
    phone: '010-4444-5555',
    email: 'choi@example.com',
    address: '서울시 용산구 이태원로 88',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'B-',
    allergies: '라텍스',
    isActive: true,
    firstVisitDate: '2025-02-14',
    lastVisitDate: '2026-05-15',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-7',
    patientNo: 'P-202500007',
    name: '강준혁',
    birthDate: '1970-04-25',
    gender: 'MALE',
    phone: '010-6666-7777',
    address: '경기도 성남시 분당구 판교로 200',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'O-',
    specialNotes: '허리디스크 수술 이력(2022)',
    isActive: true,
    firstVisitDate: '2025-01-08',
    lastVisitDate: '2026-05-26',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-8',
    patientNo: 'P-202500008',
    name: '윤서희',
    birthDate: '2015-07-19',
    gender: 'FEMALE',
    phone: '010-8888-9999',
    guardianName: '윤태호',
    guardianPhone: '010-8888-9900',
    guardianRelation: '부',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'A+',
    isActive: true,
    firstVisitDate: '2025-05-20',
    lastVisitDate: '2026-05-10',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-9',
    patientNo: 'P-202500009',
    name: '임재원',
    birthDate: '1955-02-28',
    gender: 'MALE',
    phone: '010-0011-2233',
    address: '서울시 노원구 동일로 45',
    insuranceType: 'MEDICAL_AID_2',
    bloodType: 'AB+',
    specialNotes: '만성 폐쇄성 폐질환(COPD) 이력, 흡연 30년',
    isActive: true,
    firstVisitDate: '2025-03-11',
    lastVisitDate: '2026-05-26',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-10',
    patientNo: 'P-202500010',
    name: '송미경',
    birthDate: '1992-09-07',
    gender: 'FEMALE',
    phone: '010-1122-3344',
    email: 'song@example.com',
    address: '서울시 강서구 공항대로 120',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'O+',
    allergies: '트리메토프림',
    isActive: true,
    firstVisitDate: '2025-07-22',
    lastVisitDate: '2026-05-22',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'patient-11',
    patientNo: 'P-202600011',
    name: '오태양',
    birthDate: '1983-12-12',
    gender: 'MALE',
    phone: '010-5544-6677',
    address: '인천시 남동구 소래로 300',
    insuranceType: 'HEALTH_INSURANCE',
    bloodType: 'B+',
    isActive: true,
    firstVisitDate: '2026-05-20',
    lastVisitDate: '2026-05-20',
    createdAt: now(),
    updatedAt: now(),
  },
];

// ── Appointments ──────────────────────────────────────────────────
const today = new Date().toISOString().split('T')[0];
export const appointments: Appointment[] = [
  // ── 오늘 (TODAY) ──
  {
    id: 'appt-1',
    appointmentNo: 'A-202400001',
    patientId: 'patient-1',
    patientName: '홍길동',
    patientNo: 'P-202400001',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: `${today}T09:00:00.000Z`,
    duration: 20,
    status: 'SCHEDULED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '고혈압 정기 진료',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-2',
    appointmentNo: 'A-202400002',
    patientId: 'patient-2',
    patientName: '김영희',
    patientNo: 'P-202400002',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: `${today}T10:00:00.000Z`,
    duration: 20,
    status: 'WAITING',
    queueNo: 2,
    visitType: 'REVISIT',
    chiefComplaint: '복통, 소화불량',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-3',
    appointmentNo: 'A-202400003',
    patientId: 'patient-3',
    patientName: '박철수',
    patientNo: 'P-202400003',
    doctorId: 'user-doctor-2',
    doctorName: '이서연',
    departmentId: 'dept-2',
    departmentName: '외과',
    scheduledAt: `${today}T14:00:00.000Z`,
    duration: 30,
    status: 'SCHEDULED',
    queueNo: 1,
    visitType: 'OUTPATIENT',
    chiefComplaint: '무릎 통증',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-4',
    appointmentNo: 'A-202600004',
    patientId: 'patient-5',
    patientName: '정도현',
    patientNo: 'P-202400005',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: `${today}T11:00:00.000Z`,
    duration: 20,
    status: 'IN_PROGRESS',
    queueNo: 3,
    visitType: 'REVISIT',
    chiefComplaint: '당뇨 합병증 모니터링',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-5',
    appointmentNo: 'A-202600005',
    patientId: 'patient-10',
    patientName: '송미경',
    patientNo: 'P-202500010',
    doctorId: 'user-doctor-5',
    doctorName: '신유진',
    departmentId: 'dept-5',
    departmentName: '신경과',
    scheduledAt: `${today}T13:00:00.000Z`,
    duration: 20,
    status: 'WAITING',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '편두통 재발',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-6',
    appointmentNo: 'A-202600006',
    patientId: 'patient-7',
    patientName: '강준혁',
    patientNo: 'P-202500007',
    doctorId: 'user-doctor-4',
    doctorName: '박정우',
    departmentId: 'dept-4',
    departmentName: '정형외과',
    scheduledAt: `${today}T15:00:00.000Z`,
    duration: 30,
    status: 'SCHEDULED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '요통 악화',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-7',
    appointmentNo: 'A-202600007',
    patientId: 'patient-4',
    patientName: '이미래',
    patientNo: 'P-202400004',
    doctorId: 'user-doctor-3',
    doctorName: '최신호',
    departmentId: 'dept-3',
    departmentName: '소아과',
    scheduledAt: `${today}T16:00:00.000Z`,
    duration: 20,
    status: 'SCHEDULED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '성장 정기 검진',
    createdAt: now(),
    updatedAt: now(),
  },

  // ── 어제 (2026-05-28) ──
  {
    id: 'appt-8',
    appointmentNo: 'A-202600008',
    patientId: 'patient-5',
    patientName: '정도현',
    patientNo: 'P-202400005',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: '2026-05-28T09:30:00.000Z',
    duration: 20,
    status: 'COMPLETED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '감기 증상, 인후통',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-9',
    appointmentNo: 'A-202600009',
    patientId: 'patient-2',
    patientName: '김영희',
    patientNo: 'P-202400002',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: '2026-05-28T11:00:00.000Z',
    duration: 20,
    status: 'COMPLETED',
    queueNo: 2,
    visitType: 'OUTPATIENT',
    chiefComplaint: '복통, 구역감',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-10',
    appointmentNo: 'A-202600010',
    patientId: 'patient-3',
    patientName: '박철수',
    patientNo: 'P-202400003',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: '2026-05-28T14:00:00.000Z',
    duration: 20,
    status: 'COMPLETED',
    queueNo: 3,
    visitType: 'REVISIT',
    chiefComplaint: '당뇨 관리',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-11',
    appointmentNo: 'A-202600011',
    patientId: 'patient-6',
    patientName: '최은지',
    patientNo: 'P-202500006',
    doctorId: 'user-doctor-2',
    doctorName: '이서연',
    departmentId: 'dept-6',
    departmentName: '피부과',
    scheduledAt: '2026-05-28T10:00:00.000Z',
    duration: 15,
    status: 'NO_SHOW',
    queueNo: 1,
    visitType: 'OUTPATIENT',
    chiefComplaint: '두드러기 재발',
    createdAt: now(),
    updatedAt: now(),
  },

  // ── 3일 전 (2026-05-26) ──
  {
    id: 'appt-12',
    appointmentNo: 'A-202600012',
    patientId: 'patient-7',
    patientName: '강준혁',
    patientNo: 'P-202500007',
    doctorId: 'user-doctor-4',
    doctorName: '박정우',
    departmentId: 'dept-4',
    departmentName: '정형외과',
    scheduledAt: '2026-05-26T09:00:00.000Z',
    duration: 30,
    status: 'COMPLETED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '허리 통증, 다리 저림',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-13',
    appointmentNo: 'A-202600013',
    patientId: 'patient-9',
    patientName: '임재원',
    patientNo: 'P-202500009',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: '2026-05-26T13:00:00.000Z',
    duration: 30,
    status: 'COMPLETED',
    queueNo: 2,
    visitType: 'OUTPATIENT',
    chiefComplaint: '호흡 곤란, 기침, 발열',
    createdAt: now(),
    updatedAt: now(),
  },

  // ── 1주일 전 (2026-05-22) ──
  {
    id: 'appt-14',
    appointmentNo: 'A-202600014',
    patientId: 'patient-1',
    patientName: '홍길동',
    patientNo: 'P-202400001',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: '2026-05-22T09:00:00.000Z',
    duration: 20,
    status: 'COMPLETED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '두통, 혈압 조절',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-15',
    appointmentNo: 'A-202600015',
    patientId: 'patient-10',
    patientName: '송미경',
    patientNo: 'P-202500010',
    doctorId: 'user-doctor-5',
    doctorName: '신유진',
    departmentId: 'dept-5',
    departmentName: '신경과',
    scheduledAt: '2026-05-22T11:00:00.000Z',
    duration: 20,
    status: 'CANCELLED',
    queueNo: 2,
    visitType: 'OUTPATIENT',
    chiefComplaint: '편두통',
    cancelReason: '환자 개인 사정으로 취소',
    createdAt: now(),
    updatedAt: now(),
  },

  // ── 내일 (2026-05-30) ──
  {
    id: 'appt-16',
    appointmentNo: 'A-202600016',
    patientId: 'patient-1',
    patientName: '홍길동',
    patientNo: 'P-202400001',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    departmentId: 'dept-1',
    departmentName: '내과',
    scheduledAt: '2026-05-30T09:00:00.000Z',
    duration: 20,
    status: 'SCHEDULED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '고혈압 추적 관찰',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'appt-17',
    appointmentNo: 'A-202600017',
    patientId: 'patient-11',
    patientName: '오태양',
    patientNo: 'P-202600011',
    doctorId: 'user-doctor-2',
    doctorName: '이서연',
    departmentId: 'dept-2',
    departmentName: '외과',
    scheduledAt: '2026-05-30T14:00:00.000Z',
    duration: 30,
    status: 'SCHEDULED',
    queueNo: 1,
    visitType: 'REVISIT',
    chiefComplaint: '복부 통증 추적',
    createdAt: now(),
    updatedAt: now(),
  },

  // ── 다음 주 (2026-06-05) ──
  {
    id: 'appt-18',
    appointmentNo: 'A-202600018',
    patientId: 'patient-8',
    patientName: '윤서희',
    patientNo: 'P-202500008',
    doctorId: 'user-doctor-3',
    doctorName: '최신호',
    departmentId: 'dept-3',
    departmentName: '소아과',
    scheduledAt: '2026-06-05T10:00:00.000Z',
    duration: 20,
    status: 'SCHEDULED',
    queueNo: 1,
    visitType: 'OUTPATIENT',
    chiefComplaint: '발열, 편도 부음',
    createdAt: now(),
    updatedAt: now(),
  },
];

// ── Medical Records ───────────────────────────────────────────────
export const medicalRecords: MedicalRecord[] = [
  {
    id: 'record-1',
    recordNo: 'R-202600001',
    patientId: 'patient-1',
    patientName: '홍길동',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    appointmentId: 'appt-14',
    subjective: '2주 전부터 두통과 어지러움 호소. 아침에 혈압 높게 측정됨.',
    objective: '혈압 148/94, 맥박 76, 체온 36.4°C, SpO2 98%',
    assessment: '본태성 고혈압 – 약물 용량 조정 필요',
    plan: '아모잘탄 용량 증량(5→10mg), 저염식 권고, 2주 후 재진',
    vitalSigns: { bp: '148/94', pulse: 76, temperature: 36.4, spo2: 98, height: 175, weight: 82 },
    status: 'COMPLETED',
    visitDate: '2026-05-22T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-1',
        medicalRecordId: 'record-1',
        icd10CodeId: 'icd-1',
        icd10Code: { id: 'icd-1', code: 'I10', descriptionEn: 'Essential hypertension', descriptionKo: '본태성 고혈압', category: 'I00-I99' },
        isPrimary: true,
        notes: '조절 불량, 용량 증량 결정',
        createdAt: now(),
      },
      {
        id: 'diag-2',
        medicalRecordId: 'record-1',
        icd10CodeId: 'icd-7',
        icd10Code: { id: 'icd-7', code: 'R51', descriptionEn: 'Headache', descriptionKo: '두통', category: 'R00-R99' },
        isPrimary: false,
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-1',
        medicalRecordId: 'record-1',
        testName: '공복혈당',
        testCode: 'FBG',
        result: '102',
        unit: 'mg/dL',
        referenceRange: '70-99',
        isAbnormal: true,
        severity: 'MILD',
        testedAt: '2026-05-22T08:00:00.000Z',
        createdAt: now(),
      },
      {
        id: 'lab-2',
        medicalRecordId: 'record-1',
        testName: '총콜레스테롤',
        testCode: 'TC',
        result: '215',
        unit: 'mg/dL',
        referenceRange: '<200',
        isAbnormal: true,
        severity: 'MILD',
        testedAt: '2026-05-22T08:00:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-2',
    recordNo: 'R-202600002',
    patientId: 'patient-3',
    patientName: '박철수',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    appointmentId: 'appt-10',
    subjective: '당뇨약 복용 중. 공복혈당 여전히 높음. 발 저림 호소.',
    objective: '공복혈당 178mg/dL, HbA1c 8.0%, 체중 88kg',
    assessment: '제2형 당뇨병 – 혈당 조절 불량, 말초신경병증 의심',
    plan: '메트포르민 증량, 신경병증 검사 의뢰, 4주 후 재진',
    vitalSigns: { bp: '132/86', pulse: 80, temperature: 36.6, spo2: 97, weight: 88 },
    status: 'COMPLETED',
    visitDate: '2026-05-28T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-3',
        medicalRecordId: 'record-2',
        icd10CodeId: 'icd-2',
        icd10Code: { id: 'icd-2', code: 'E11', descriptionEn: 'Type 2 diabetes mellitus', descriptionKo: '제2형 당뇨병', category: 'E00-E89' },
        isPrimary: true,
        notes: '혈당 조절 불량, 메트포르민 증량',
        createdAt: now(),
      },
      {
        id: 'diag-4',
        medicalRecordId: 'record-2',
        icd10CodeId: 'icd-1',
        icd10Code: { id: 'icd-1', code: 'I10', descriptionEn: 'Essential hypertension', descriptionKo: '본태성 고혈압', category: 'I00-I99' },
        isPrimary: false,
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-3',
        medicalRecordId: 'record-2',
        testName: '공복혈당',
        testCode: 'FBG',
        result: '178',
        unit: 'mg/dL',
        referenceRange: '70-99',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-05-28T08:30:00.000Z',
        createdAt: now(),
      },
      {
        id: 'lab-4',
        medicalRecordId: 'record-2',
        testName: '당화혈색소(HbA1c)',
        testCode: 'HBA1C',
        result: '8.0',
        unit: '%',
        referenceRange: '<6.5',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-05-28T08:30:00.000Z',
        createdAt: now(),
      },
      {
        id: 'lab-5',
        medicalRecordId: 'record-2',
        testName: '크레아티닌',
        testCode: 'CRE',
        result: '1.1',
        unit: 'mg/dL',
        referenceRange: '0.7-1.2',
        isAbnormal: false,
        severity: 'NORMAL',
        testedAt: '2026-05-28T08:30:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-3',
    recordNo: 'R-202600003',
    patientId: 'patient-5',
    patientName: '정도현',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    appointmentId: 'appt-8',
    subjective: '3일 전부터 인후통, 콧물, 미열. 직장 동료도 비슷한 증상.',
    objective: '체온 37.8°C, 인두 발적, 편도 비대 없음',
    assessment: '급성 상기도 감염',
    plan: '해열진통제, 항히스타민제 처방. 충분한 휴식 권고. 증상 지속 시 재진.',
    vitalSigns: { bp: '118/76', pulse: 88, temperature: 37.8, spo2: 99 },
    status: 'COMPLETED',
    visitDate: '2026-05-28T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-5',
        medicalRecordId: 'record-3',
        icd10CodeId: 'icd-3',
        icd10Code: { id: 'icd-3', code: 'J06.9', descriptionEn: 'Acute upper respiratory infection', descriptionKo: '급성 상기도 감염', category: 'J00-J99' },
        isPrimary: true,
        createdAt: now(),
      },
    ],
    labResults: [],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-4',
    recordNo: 'R-202600004',
    patientId: 'patient-2',
    patientName: '김영희',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    appointmentId: 'appt-9',
    subjective: '명치 부위 통증, 식후 더 심해짐. 역류감, 구역감. 스트레스 많음.',
    objective: '상복부 압통 (+), 반발통 (-), 장음 정상',
    assessment: '급성 위염',
    plan: '위산억제제(판토프라졸) 처방, 자극적 음식 회피, 스트레스 관리 권고',
    vitalSigns: { bp: '112/70', pulse: 74, temperature: 36.5, spo2: 99 },
    status: 'COMPLETED',
    visitDate: '2026-05-28T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-6',
        medicalRecordId: 'record-4',
        icd10CodeId: 'icd-4',
        icd10Code: { id: 'icd-4', code: 'K29.7', descriptionEn: 'Gastritis, unspecified', descriptionKo: '상세불명의 위염', category: 'K00-K93' },
        isPrimary: true,
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-6',
        medicalRecordId: 'record-4',
        testName: 'H.pylori 항원 검사',
        testCode: 'HP-AG',
        result: '음성',
        unit: '',
        referenceRange: '음성',
        isAbnormal: false,
        severity: 'NORMAL',
        testedAt: '2026-05-28T10:00:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-5',
    recordNo: 'R-202600005',
    patientId: 'patient-7',
    patientName: '강준혁',
    doctorId: 'user-doctor-4',
    doctorName: '박정우',
    appointmentId: 'appt-12',
    subjective: '좌측 허리 통증이 2주 전부터 심해짐. 좌측 다리까지 저림 증상. 장시간 앉아있으면 악화.',
    objective: 'SLR test (+) 좌측, 좌측 무릎반사 감소, 요추 4-5번 압통',
    assessment: '요추간판 탈출증 (L4-5)',
    plan: 'MRI 촬영 의뢰, 소염진통제 처방, 물리치료 권고',
    vitalSigns: { bp: '124/80', pulse: 72, temperature: 36.3, spo2: 99 },
    status: 'COMPLETED',
    visitDate: '2026-05-26T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-7',
        medicalRecordId: 'record-5',
        icd10CodeId: 'icd-5',
        icd10Code: { id: 'icd-5', code: 'M54.5', descriptionEn: 'Low back pain', descriptionKo: '요통', category: 'M00-M99' },
        isPrimary: true,
        notes: 'L4-5 디스크 탈출 의심, MRI 의뢰',
        createdAt: now(),
      },
    ],
    labResults: [],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-6',
    recordNo: 'R-202600006',
    patientId: 'patient-9',
    patientName: '임재원',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    appointmentId: 'appt-13',
    subjective: '5일 전부터 고열(38.5°C), 기침, 가래. 호흡 시 흉통. 기력 저하.',
    objective: '체온 38.6°C, 호흡수 22회/분, SpO2 93%, 좌하폐야 수포음',
    assessment: '지역사회 획득 폐렴 (좌하엽)',
    plan: '항생제(아목시실린-클라불라네이트) 처방, 1주 후 재진, 증상 악화 시 즉시 내원',
    vitalSigns: { bp: '136/88', pulse: 96, temperature: 38.6, spo2: 93, respiratoryRate: 22 },
    status: 'COMPLETED',
    visitDate: '2026-05-26T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-8',
        medicalRecordId: 'record-6',
        icd10CodeId: 'icd-6',
        icd10Code: { id: 'icd-6', code: 'J18.9', descriptionEn: 'Pneumonia, unspecified', descriptionKo: '상세불명의 폐렴', category: 'J00-J99' },
        isPrimary: true,
        notes: '지역사회 획득 폐렴, 항생제 치료 시작',
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-7',
        medicalRecordId: 'record-6',
        testName: 'CRP (C반응단백)',
        testCode: 'CRP',
        result: '68.4',
        unit: 'mg/L',
        referenceRange: '<5',
        isAbnormal: true,
        severity: 'CRITICAL',
        testedAt: '2026-05-26T13:30:00.000Z',
        createdAt: now(),
      },
      {
        id: 'lab-8',
        medicalRecordId: 'record-6',
        testName: 'WBC (백혈구)',
        testCode: 'WBC',
        result: '14200',
        unit: '/μL',
        referenceRange: '4000-10000',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-05-26T13:30:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-7',
    recordNo: 'R-202600007',
    patientId: 'patient-10',
    patientName: '송미경',
    doctorId: 'user-doctor-5',
    doctorName: '신유진',
    appointmentId: 'appt-14',
    subjective: '한쪽(우측) 머리 욱신거리는 통증, 빛과 소리에 민감, 구역감. 월 3-4회 발작.',
    objective: '신경학적 검진 정상, 두부 CT 이상 소견 없음',
    assessment: '편두통 (조짐 없는 편두통)',
    plan: '트립탄 계열 약물 처방, 통증 일지 기록 권고, 유발 인자 파악',
    vitalSigns: { bp: '110/68', pulse: 66, temperature: 36.2, spo2: 100 },
    status: 'COMPLETED',
    visitDate: '2026-05-22T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-9',
        medicalRecordId: 'record-7',
        icd10CodeId: 'icd-11',
        icd10Code: { id: 'icd-11', code: 'G43.9', descriptionEn: 'Migraine, unspecified', descriptionKo: '상세불명의 편두통', category: 'G00-G99' },
        isPrimary: true,
        createdAt: now(),
      },
    ],
    labResults: [],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-8',
    recordNo: 'R-202600008',
    patientId: 'patient-6',
    patientName: '최은지',
    doctorId: 'user-doctor-2',
    doctorName: '이서연',
    subjective: '전신 두드러기 3일째. 특별한 음식 변화 없음. 새 화장품 사용 후 발생.',
    objective: '전신 팽진 및 홍반, 소양감 심함. 혈압 정상.',
    assessment: '접촉성 두드러기 (화장품 성분 의심)',
    plan: '항히스타민제 처방, 원인 물질 회피, 패치 테스트 예약',
    vitalSigns: { bp: '118/72', pulse: 78, temperature: 36.5, spo2: 99 },
    status: 'COMPLETED',
    visitDate: '2026-05-15T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-10',
        medicalRecordId: 'record-8',
        icd10CodeId: 'icd-12',
        icd10Code: { id: 'icd-12', code: 'L50.0', descriptionEn: 'Allergic urticaria', descriptionKo: '알레르기성 두드러기', category: 'L00-L99' },
        isPrimary: true,
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-9',
        medicalRecordId: 'record-8',
        testName: '총 IgE',
        testCode: 'IgE',
        result: '285',
        unit: 'IU/mL',
        referenceRange: '<100',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-05-15T10:30:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-9',
    recordNo: 'R-202600009',
    patientId: 'patient-4',
    patientName: '이미래',
    doctorId: 'user-doctor-3',
    doctorName: '최신호',
    subjective: '발열(38.2°C), 목 통증, 음식물 삼키기 힘듦. 어제부터 시작.',
    objective: '체온 38.3°C, 편도 비대 및 삼출물, 경부 림프절 촉지',
    assessment: '급성 편도염',
    plan: '항생제(아목시실린) 처방, 충분한 수분 섭취, 3일 후 재진',
    vitalSigns: { bp: '105/65', pulse: 92, temperature: 38.3, spo2: 98 },
    status: 'COMPLETED',
    visitDate: '2026-05-10T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-11',
        medicalRecordId: 'record-9',
        icd10CodeId: 'icd-13',
        icd10Code: { id: 'icd-13', code: 'J03.9', descriptionEn: 'Acute tonsillitis, unspecified', descriptionKo: '상세불명의 급성 편도염', category: 'J00-J99' },
        isPrimary: true,
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-10',
        medicalRecordId: 'record-9',
        testName: 'A군 연쇄구균 신속항원검사',
        testCode: 'RADT',
        result: '양성',
        unit: '',
        referenceRange: '음성',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-05-10T15:30:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-10',
    recordNo: 'R-202600010',
    patientId: 'patient-11',
    patientName: '오태양',
    doctorId: 'user-doctor-2',
    doctorName: '이서연',
    subjective: '우하복부 통증 1일째. 처음엔 배꼽 주위에서 시작해 우하복부로 이동.',
    objective: '우하복부 압통(+), McBurney점 압통(+), Rebound 압통(+), 발열 37.9°C',
    assessment: '급성 충수염',
    plan: '즉각적인 충수돌기절제술 시행, 수술 전 검사 진행',
    vitalSigns: { bp: '128/82', pulse: 104, temperature: 37.9, spo2: 98 },
    status: 'COMPLETED',
    visitDate: '2026-05-20T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-12',
        medicalRecordId: 'record-10',
        icd10CodeId: 'icd-14',
        icd10Code: { id: 'icd-14', code: 'K37', descriptionEn: 'Unspecified appendicitis', descriptionKo: '상세불명의 충수염', category: 'K00-K93' },
        isPrimary: true,
        notes: '수술적 치료 필요',
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-11',
        medicalRecordId: 'record-10',
        testName: 'WBC (백혈구)',
        testCode: 'WBC',
        result: '16800',
        unit: '/μL',
        referenceRange: '4000-10000',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-05-20T20:00:00.000Z',
        createdAt: now(),
      },
      {
        id: 'lab-12',
        medicalRecordId: 'record-10',
        testName: 'CRP (C반응단백)',
        testCode: 'CRP',
        result: '42.1',
        unit: 'mg/L',
        referenceRange: '<5',
        isAbnormal: true,
        severity: 'CRITICAL',
        testedAt: '2026-05-20T20:00:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-11',
    recordNo: 'R-202600011',
    patientId: 'patient-3',
    patientName: '박철수',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    subjective: '당뇨 진단 후 첫 내원. 공복혈당 높다는 건강검진 결과 가져옴.',
    objective: '공복혈당 185mg/dL, HbA1c 8.2%',
    assessment: '제2형 당뇨병 (신규 진단)',
    plan: '메트포르민 500mg 처방, 식이조절 교육, 4주 후 재진',
    vitalSigns: { bp: '130/85', pulse: 82, temperature: 36.7, spo2: 97, weight: 90 },
    status: 'COMPLETED',
    visitDate: '2026-03-10T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-13',
        medicalRecordId: 'record-11',
        icd10CodeId: 'icd-2',
        icd10Code: { id: 'icd-2', code: 'E11', descriptionEn: 'Type 2 diabetes mellitus', descriptionKo: '제2형 당뇨병', category: 'E00-E89' },
        isPrimary: true,
        notes: '신규 진단, 메트포르민 시작',
        createdAt: now(),
      },
    ],
    labResults: [
      {
        id: 'lab-13',
        medicalRecordId: 'record-11',
        testName: '공복혈당',
        testCode: 'FBG',
        result: '185',
        unit: 'mg/dL',
        referenceRange: '70-99',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-03-10T08:00:00.000Z',
        createdAt: now(),
      },
      {
        id: 'lab-14',
        medicalRecordId: 'record-11',
        testName: '당화혈색소(HbA1c)',
        testCode: 'HBA1C',
        result: '8.2',
        unit: '%',
        referenceRange: '<6.5',
        isAbnormal: true,
        severity: 'MODERATE',
        testedAt: '2026-03-10T08:00:00.000Z',
        createdAt: now(),
      },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'record-12',
    recordNo: 'R-202600012',
    patientId: 'patient-1',
    patientName: '홍길동',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    subjective: '고혈압 첫 진단. 3개월 전 직장 검진에서 혈압 높다는 소견.',
    objective: '혈압 152/96, 맥박 78, 체온 36.5°C',
    assessment: '본태성 고혈압 (신규 진단)',
    plan: '아모잘탄 5mg 처방, 저염식/절주 권고, 1개월 후 재진',
    vitalSigns: { bp: '152/96', pulse: 78, temperature: 36.5, spo2: 98, height: 175, weight: 80 },
    status: 'COMPLETED',
    visitDate: '2026-01-15T00:00:00.000Z',
    diagnoses: [
      {
        id: 'diag-14',
        medicalRecordId: 'record-12',
        icd10CodeId: 'icd-1',
        icd10Code: { id: 'icd-1', code: 'I10', descriptionEn: 'Essential hypertension', descriptionKo: '본태성 고혈압', category: 'I00-I99' },
        isPrimary: true,
        notes: '신규 진단, 아모잘탄 5mg 시작',
        createdAt: now(),
      },
    ],
    labResults: [],
    createdAt: now(),
    updatedAt: now(),
  },
];

// ── ICD-10 Codes ──────────────────────────────────────────────────
export const icd10Codes: ICD10Code[] = [
  { id: 'icd-1',  code: 'I10',   descriptionEn: 'Essential hypertension',            descriptionKo: '본태성 고혈압',          category: 'I00-I99' },
  { id: 'icd-2',  code: 'E11',   descriptionEn: 'Type 2 diabetes mellitus',           descriptionKo: '제2형 당뇨병',           category: 'E00-E89' },
  { id: 'icd-3',  code: 'J06.9', descriptionEn: 'Acute upper respiratory infection',  descriptionKo: '급성 상기도 감염',       category: 'J00-J99' },
  { id: 'icd-4',  code: 'K29.7', descriptionEn: 'Gastritis, unspecified',             descriptionKo: '상세불명의 위염',        category: 'K00-K93' },
  { id: 'icd-5',  code: 'M54.5', descriptionEn: 'Low back pain',                      descriptionKo: '요통',                   category: 'M00-M99' },
  { id: 'icd-6',  code: 'J18.9', descriptionEn: 'Pneumonia, unspecified',             descriptionKo: '상세불명의 폐렴',        category: 'J00-J99' },
  { id: 'icd-7',  code: 'R51',   descriptionEn: 'Headache',                           descriptionKo: '두통',                   category: 'R00-R99' },
  { id: 'icd-8',  code: 'A09',   descriptionEn: 'Gastroenteritis',                    descriptionKo: '위장염',                 category: 'A00-B99' },
  { id: 'icd-9',  code: 'F32.9', descriptionEn: 'Major depressive disorder',          descriptionKo: '주요우울장애',           category: 'F00-F99' },
  { id: 'icd-10', code: 'N39.0', descriptionEn: 'Urinary tract infection',            descriptionKo: '요로감염',               category: 'N00-N99' },
  { id: 'icd-11', code: 'G43.9', descriptionEn: 'Migraine, unspecified',              descriptionKo: '상세불명의 편두통',      category: 'G00-G99' },
  { id: 'icd-12', code: 'L50.0', descriptionEn: 'Allergic urticaria',                 descriptionKo: '알레르기성 두드러기',    category: 'L00-L99' },
  { id: 'icd-13', code: 'J03.9', descriptionEn: 'Acute tonsillitis, unspecified',     descriptionKo: '상세불명의 급성 편도염', category: 'J00-J99' },
  { id: 'icd-14', code: 'K37',   descriptionEn: 'Unspecified appendicitis',           descriptionKo: '상세불명의 충수염',      category: 'K00-K93' },
  { id: 'icd-15', code: 'E78.5', descriptionEn: 'Hyperlipidemia, unspecified',        descriptionKo: '상세불명의 고지혈증',    category: 'E00-E89' },
  { id: 'icd-16', code: 'J45.9', descriptionEn: 'Asthma, unspecified',                descriptionKo: '상세불명의 천식',        category: 'J00-J99' },
  { id: 'icd-17', code: 'M17.1', descriptionEn: 'Primary gonarthrosis, unilateral',  descriptionKo: '일측성 원발성 무릎 관절증', category: 'M00-M99' },
];

export const recordDiagnoses: RecordDiagnosis[] = [
  { id: 'diag-1',  medicalRecordId: 'record-1',  icd10CodeId: 'icd-1',  isPrimary: true,  notes: '조절 불량, 용량 증량 결정', createdAt: now() },
  { id: 'diag-2',  medicalRecordId: 'record-1',  icd10CodeId: 'icd-7',  isPrimary: false, createdAt: now() },
  { id: 'diag-3',  medicalRecordId: 'record-2',  icd10CodeId: 'icd-2',  isPrimary: true,  notes: '혈당 조절 불량, 메트포르민 증량', createdAt: now() },
  { id: 'diag-4',  medicalRecordId: 'record-2',  icd10CodeId: 'icd-1',  isPrimary: false, createdAt: now() },
  { id: 'diag-5',  medicalRecordId: 'record-3',  icd10CodeId: 'icd-3',  isPrimary: true,  createdAt: now() },
  { id: 'diag-6',  medicalRecordId: 'record-4',  icd10CodeId: 'icd-4',  isPrimary: true,  createdAt: now() },
  { id: 'diag-7',  medicalRecordId: 'record-5',  icd10CodeId: 'icd-5',  isPrimary: true,  notes: 'L4-5 디스크 탈출 의심, MRI 의뢰', createdAt: now() },
  { id: 'diag-8',  medicalRecordId: 'record-6',  icd10CodeId: 'icd-6',  isPrimary: true,  notes: '지역사회 획득 폐렴, 항생제 치료 시작', createdAt: now() },
  { id: 'diag-9',  medicalRecordId: 'record-7',  icd10CodeId: 'icd-11', isPrimary: true,  createdAt: now() },
  { id: 'diag-10', medicalRecordId: 'record-8',  icd10CodeId: 'icd-12', isPrimary: true,  createdAt: now() },
  { id: 'diag-11', medicalRecordId: 'record-9',  icd10CodeId: 'icd-13', isPrimary: true,  createdAt: now() },
  { id: 'diag-12', medicalRecordId: 'record-10', icd10CodeId: 'icd-14', isPrimary: true,  notes: '수술적 치료 필요', createdAt: now() },
  { id: 'diag-13', medicalRecordId: 'record-11', icd10CodeId: 'icd-2',  isPrimary: true,  notes: '신규 진단, 메트포르민 시작', createdAt: now() },
  { id: 'diag-14', medicalRecordId: 'record-12', icd10CodeId: 'icd-1',  isPrimary: true,  notes: '신규 진단, 아모잘탄 5mg 시작', createdAt: now() },
];

export const labResults: LabResult[] = [
  { id: 'lab-1',  medicalRecordId: 'record-1',  testName: '공복혈당',               testCode: 'FBG',    result: '102',  unit: 'mg/dL', referenceRange: '70-99',    isAbnormal: true,  severity: 'MILD',     testedAt: '2026-05-22T08:00:00.000Z', createdAt: now() },
  { id: 'lab-2',  medicalRecordId: 'record-1',  testName: '총콜레스테롤',             testCode: 'TC',     result: '215',  unit: 'mg/dL', referenceRange: '<200',     isAbnormal: true,  severity: 'MILD',     testedAt: '2026-05-22T08:00:00.000Z', createdAt: now() },
  { id: 'lab-3',  medicalRecordId: 'record-2',  testName: '공복혈당',               testCode: 'FBG',    result: '178',  unit: 'mg/dL', referenceRange: '70-99',    isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-05-28T08:30:00.000Z', createdAt: now() },
  { id: 'lab-4',  medicalRecordId: 'record-2',  testName: '당화혈색소(HbA1c)',       testCode: 'HBA1C',  result: '8.0',  unit: '%',     referenceRange: '<6.5',     isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-05-28T08:30:00.000Z', createdAt: now() },
  { id: 'lab-5',  medicalRecordId: 'record-2',  testName: '크레아티닌',              testCode: 'CRE',    result: '1.1',  unit: 'mg/dL', referenceRange: '0.7-1.2',  isAbnormal: false, severity: 'NORMAL',   testedAt: '2026-05-28T08:30:00.000Z', createdAt: now() },
  { id: 'lab-6',  medicalRecordId: 'record-4',  testName: 'H.pylori 항원 검사',     testCode: 'HP-AG',  result: '음성', unit: '',      referenceRange: '음성',     isAbnormal: false, severity: 'NORMAL',   testedAt: '2026-05-28T10:00:00.000Z', createdAt: now() },
  { id: 'lab-7',  medicalRecordId: 'record-6',  testName: 'CRP (C반응단백)',        testCode: 'CRP',    result: '68.4', unit: 'mg/L',  referenceRange: '<5',       isAbnormal: true,  severity: 'CRITICAL', testedAt: '2026-05-26T13:30:00.000Z', createdAt: now() },
  { id: 'lab-8',  medicalRecordId: 'record-6',  testName: 'WBC (백혈구)',           testCode: 'WBC',    result: '14200',unit: '/μL',   referenceRange: '4000-10000',isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-05-26T13:30:00.000Z', createdAt: now() },
  { id: 'lab-9',  medicalRecordId: 'record-8',  testName: '총 IgE',               testCode: 'IgE',    result: '285',  unit: 'IU/mL', referenceRange: '<100',     isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-05-15T10:30:00.000Z', createdAt: now() },
  { id: 'lab-10', medicalRecordId: 'record-9',  testName: 'A군 연쇄구균 신속항원검사', testCode: 'RADT',   result: '양성', unit: '',      referenceRange: '음성',     isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-05-10T15:30:00.000Z', createdAt: now() },
  { id: 'lab-11', medicalRecordId: 'record-10', testName: 'WBC (백혈구)',           testCode: 'WBC',    result: '16800',unit: '/μL',   referenceRange: '4000-10000',isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-05-20T20:00:00.000Z', createdAt: now() },
  { id: 'lab-12', medicalRecordId: 'record-10', testName: 'CRP (C반응단백)',        testCode: 'CRP',    result: '42.1', unit: 'mg/L',  referenceRange: '<5',       isAbnormal: true,  severity: 'CRITICAL', testedAt: '2026-05-20T20:00:00.000Z', createdAt: now() },
  { id: 'lab-13', medicalRecordId: 'record-11', testName: '공복혈당',               testCode: 'FBG',    result: '185',  unit: 'mg/dL', referenceRange: '70-99',    isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-03-10T08:00:00.000Z', createdAt: now() },
  { id: 'lab-14', medicalRecordId: 'record-11', testName: '당화혈색소(HbA1c)',       testCode: 'HBA1C',  result: '8.2',  unit: '%',     referenceRange: '<6.5',     isAbnormal: true,  severity: 'MODERATE', testedAt: '2026-03-10T08:00:00.000Z', createdAt: now() },
];

// ── Medications ───────────────────────────────────────────────────
export const medications: Medication[] = [
  { id: 'med-1',  code: 'MED001', name: '타이레놀 500mg',         genericName: '아세트아미노펜',        manufacturer: '한국얀센',   category: '해열진통제',   form: '정제', strength: '500mg',    unit: '정',  stockCount: 1000, minStockAlert: 100, unitPrice:  50,  requiresPrescription: false, isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-2',  code: 'MED002', name: '아모잘탄정 5/100mg',     genericName: '암로디핀/로살탄',       manufacturer: '한미약품',   category: '항고혈압제',   form: '정제', strength: '5/100mg',  unit: '정',  stockCount:  500, minStockAlert:  50, unitPrice: 380,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-3',  code: 'MED003', name: '메트포르민 500mg',       genericName: '메트포르민',            manufacturer: '대원제약',   category: '당뇨약',       form: '정제', strength: '500mg',    unit: '정',  stockCount:  800, minStockAlert:  80, unitPrice:  60,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-4',  code: 'MED004', name: '아목시실린 250mg',       genericName: '아목시실린',            manufacturer: '유한양행',   category: '항생제',       form: '캡슐', strength: '250mg',    unit: '캡슐', stockCount:  600, minStockAlert:  60, unitPrice: 120,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-5',  code: 'MED005', name: '판토록정 40mg',          genericName: '판토프라졸',            manufacturer: '동아에스티', category: '위산억제제',   form: '정제', strength: '40mg',     unit: '정',  stockCount:  400, minStockAlert:  40, unitPrice: 200,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-6',  code: 'MED006', name: '이부프로펜 400mg',       genericName: '이부프로펜',            manufacturer: '종근당',     category: '소염진통제',   form: '정제', strength: '400mg',    unit: '정',  stockCount:  750, minStockAlert:  75, unitPrice:  80,  requiresPrescription: false, isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-7',  code: 'MED007', name: '세티리진 10mg',          genericName: '세티리진',              manufacturer: '한독',       category: '항히스타민제', form: '정제', strength: '10mg',     unit: '정',  stockCount:  350, minStockAlert:  35, unitPrice:  95,  requiresPrescription: false, isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-8',  code: 'MED008', name: '아토르바스타틴 20mg',    genericName: '아토르바스타틴',        manufacturer: '화이자',     category: '고지혈증약',   form: '정제', strength: '20mg',     unit: '정',  stockCount:  300, minStockAlert:  30, unitPrice: 250,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-9',  code: 'MED009', name: '수마트립탄 50mg',        genericName: '수마트립탄',            manufacturer: '글락소스미스클라인', category: '편두통약', form: '정제', strength: '50mg', unit: '정',  stockCount:  150, minStockAlert:  20, unitPrice: 420,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-10', code: 'MED010', name: '아목시실린/클라불라네이트 625mg', genericName: '아목시실린/클라불라네이트', manufacturer: '글락소스미스클라인', category: '항생제', form: '정제', strength: '625mg', unit: '정', stockCount: 200, minStockAlert: 30, unitPrice: 280, requiresPrescription: true, isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-11', code: 'MED011', name: '메트포르민 1000mg',      genericName: '메트포르민',            manufacturer: '대원제약',   category: '당뇨약',       form: '정제', strength: '1000mg',   unit: '정',  stockCount:  600, minStockAlert:  60, unitPrice:  90,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
  { id: 'med-12', code: 'MED012', name: '아모잘탄정 10/100mg',    genericName: '암로디핀/로살탄',       manufacturer: '한미약품',   category: '항고혈압제',   form: '정제', strength: '10/100mg', unit: '정',  stockCount:  450, minStockAlert:  50, unitPrice: 420,  requiresPrescription: true,  isActive: true, createdAt: now(), updatedAt: now() },
];

// ── Prescriptions ─────────────────────────────────────────────────
export const prescriptions: (Prescription & { items: (PrescriptionItem & { medication?: Medication })[] })[] = [
  {
    id: 'presc-1',
    prescriptionNo: 'RX-202600001',
    patientId: 'patient-1',
    patientName: '홍길동',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    medicalRecordId: 'record-12',
    issuedAt: '2026-01-15T09:30:00.000Z',
    dispensedAt: '2026-01-15T10:00:00.000Z',
    dispensedBy: 'user-pharm-1',
    notes: '혈압약은 매일 아침 식후 복용. 임의로 중단하지 말 것.',
    items: [
      { id: 'pi-1', prescriptionId: 'presc-1', medicationId: 'med-2', dosage: '1정', frequency: '1일 1회 아침 식후', duration: 30, quantity: 30, medication: medications[1] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'presc-2',
    prescriptionNo: 'RX-202600002',
    patientId: 'patient-3',
    patientName: '박철수',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    medicalRecordId: 'record-11',
    issuedAt: '2026-03-10T09:00:00.000Z',
    dispensedAt: '2026-03-10T09:30:00.000Z',
    dispensedBy: 'user-pharm-1',
    notes: '식사와 함께 복용. 메스꺼움 시 음식 섭취량 줄이기.',
    items: [
      { id: 'pi-2', prescriptionId: 'presc-2', medicationId: 'med-3', dosage: '1정', frequency: '1일 2회 아침·저녁 식사 중', duration: 30, quantity: 60, medication: medications[2] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'presc-3',
    prescriptionNo: 'RX-202600003',
    patientId: 'patient-1',
    patientName: '홍길동',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    medicalRecordId: 'record-1',
    issuedAt: '2026-05-22T09:30:00.000Z',
    dispensedAt: '2026-05-22T10:10:00.000Z',
    dispensedBy: 'user-pharm-1',
    notes: '아모잘탄 10mg으로 증량. 어지러움 발생 시 즉시 연락.',
    items: [
      { id: 'pi-3', prescriptionId: 'presc-3', medicationId: 'med-12', dosage: '1정', frequency: '1일 1회 아침 식후', duration: 30, quantity: 30, medication: medications[11] },
      { id: 'pi-4', prescriptionId: 'presc-3', medicationId: 'med-8',  dosage: '1정', frequency: '1일 1회 저녁 식후', duration: 30, quantity: 30, medication: medications[7] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'presc-4',
    prescriptionNo: 'RX-202600004',
    patientId: 'patient-5',
    patientName: '정도현',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    medicalRecordId: 'record-3',
    issuedAt: '2026-05-28T09:45:00.000Z',
    dispensedAt: '2026-05-28T10:20:00.000Z',
    dispensedBy: 'user-pharm-1',
    notes: '증상 호전 시에도 처방 기간 끝까지 복용.',
    items: [
      { id: 'pi-5', prescriptionId: 'presc-4', medicationId: 'med-1', dosage: '1정', frequency: '1일 3회 식후', duration: 5, quantity: 15, medication: medications[0] },
      { id: 'pi-6', prescriptionId: 'presc-4', medicationId: 'med-7', dosage: '1정', frequency: '1일 1회 취침 전', duration: 5, quantity: 5, medication: medications[6] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'presc-5',
    prescriptionNo: 'RX-202600005',
    patientId: 'patient-2',
    patientName: '김영희',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    medicalRecordId: 'record-4',
    issuedAt: '2026-05-28T11:30:00.000Z',
    dispensedAt: '2026-05-28T12:00:00.000Z',
    dispensedBy: 'user-pharm-1',
    notes: '식전 30분에 복용. 공복 금지.',
    items: [
      { id: 'pi-7', prescriptionId: 'presc-5', medicationId: 'med-5', dosage: '1정', frequency: '1일 1회 아침 식전 30분', duration: 14, quantity: 14, medication: medications[4] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'presc-6',
    prescriptionNo: 'RX-202600006',
    patientId: 'patient-9',
    patientName: '임재원',
    doctorId: 'user-doctor-1',
    doctorName: '김민준',
    medicalRecordId: 'record-6',
    issuedAt: '2026-05-26T14:00:00.000Z',
    dispensedAt: '2026-05-26T14:30:00.000Z',
    dispensedBy: 'user-pharm-1',
    notes: '항생제는 반드시 처방 기간 끝까지 복용. 임의 중단 금지.',
    items: [
      { id: 'pi-8', prescriptionId: 'presc-6', medicationId: 'med-10', dosage: '1정', frequency: '1일 3회 식후', duration: 7, quantity: 21, medication: medications[9] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'presc-7',
    prescriptionNo: 'RX-202600007',
    patientId: 'patient-10',
    patientName: '송미경',
    doctorId: 'user-doctor-5',
    doctorName: '신유진',
    medicalRecordId: 'record-7',
    issuedAt: '2026-05-22T11:30:00.000Z',
    notes: '두통 발작 시 즉시 복용. 하루 2정 초과 금지.',
    items: [
      { id: 'pi-9', prescriptionId: 'presc-7', medicationId: 'med-9', dosage: '1정', frequency: '발작 시 복용', duration: 30, quantity: 6, medication: medications[8] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'presc-8',
    prescriptionNo: 'RX-202600008',
    patientId: 'patient-4',
    patientName: '이미래',
    doctorId: 'user-doctor-3',
    doctorName: '최신호',
    medicalRecordId: 'record-9',
    issuedAt: '2026-05-10T15:45:00.000Z',
    dispensedAt: '2026-05-10T16:10:00.000Z',
    dispensedBy: 'user-pharm-1',
    notes: '어린이 용량. 식사와 함께 복용 권장.',
    items: [
      { id: 'pi-10', prescriptionId: 'presc-8', medicationId: 'med-4', dosage: '1캡슐', frequency: '1일 3회 식후', duration: 7, quantity: 21, medication: medications[3] },
      { id: 'pi-11', prescriptionId: 'presc-8', medicationId: 'med-1', dosage: '0.5정', frequency: '발열 시 복용 (4-6시간 간격)', duration: 5, quantity: 10, medication: medications[0] },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
];

// ── Invoices ──────────────────────────────────────────────────────
export const invoices: (Invoice & { items: InvoiceItem[]; payments: Payment[] })[] = [
  {
    id: 'inv-1',
    invoiceNo: 'INV-202600001',
    patientId: 'patient-1',
    patientName: '홍길동',
    totalAmount: 32000,
    insuranceAmt: 22400,
    patientAmt: 9600,
    discountAmt: 0,
    status: 'PAID',
    notes: '',
    items: [
      { id: 'ii-1', invoiceId: 'inv-1', description: '초진진찰료', category: '진찰료', quantity: 1, unitPrice: 15000, totalPrice: 15000 },
      { id: 'ii-2', invoiceId: 'inv-1', description: '혈압약(아모잘탄 5mg) 30일분', category: '약제비', quantity: 30, unitPrice: 380, totalPrice: 11400 },
      { id: 'ii-3', invoiceId: 'inv-1', description: '고지혈증약(아토르바스타틴) 30일분', category: '약제비', quantity: 30, unitPrice: 190, totalPrice: 5600 },
    ],
    payments: [
      { id: 'pay-1', invoiceId: 'inv-1', amount: 9600, method: 'CARD', paidAt: '2026-01-15T10:05:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-2',
    invoiceNo: 'INV-202600002',
    patientId: 'patient-3',
    patientName: '박철수',
    totalAmount: 45000,
    insuranceAmt: 31500,
    patientAmt: 13500,
    discountAmt: 0,
    status: 'PAID',
    items: [
      { id: 'ii-4', invoiceId: 'inv-2', description: '초진진찰료', category: '진찰료', quantity: 1, unitPrice: 15000, totalPrice: 15000 },
      { id: 'ii-5', invoiceId: 'inv-2', description: '혈당 검사', category: '검사료', quantity: 1, unitPrice: 16200, totalPrice: 16200 },
      { id: 'ii-6', invoiceId: 'inv-2', description: '메트포르민 500mg 60일분', category: '약제비', quantity: 60, unitPrice: 60, totalPrice: 3600 },
      { id: 'ii-7', invoiceId: 'inv-2', description: 'HbA1c 검사', category: '검사료', quantity: 1, unitPrice: 10200, totalPrice: 10200 },
    ],
    payments: [
      { id: 'pay-2', invoiceId: 'inv-2', amount: 13500, method: 'CASH', paidAt: '2026-03-10T09:35:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-3',
    invoiceNo: 'INV-202600003',
    patientId: 'patient-1',
    patientName: '홍길동',
    totalAmount: 38000,
    insuranceAmt: 26600,
    patientAmt: 11400,
    discountAmt: 0,
    status: 'PAID',
    items: [
      { id: 'ii-8',  invoiceId: 'inv-3', description: '재진진찰료', category: '진찰료', quantity: 1, unitPrice: 10000, totalPrice: 10000 },
      { id: 'ii-9',  invoiceId: 'inv-3', description: '혈액검사(혈당, 콜레스테롤)', category: '검사료', quantity: 1, unitPrice: 15600, totalPrice: 15600 },
      { id: 'ii-10', invoiceId: 'inv-3', description: '아모잘탄 10mg 30일분', category: '약제비', quantity: 30, unitPrice: 420, totalPrice: 12600 },
    ],
    payments: [
      { id: 'pay-3', invoiceId: 'inv-3', amount: 11400, method: 'CARD', paidAt: '2026-05-22T10:15:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-4',
    invoiceNo: 'INV-202600004',
    patientId: 'patient-5',
    patientName: '정도현',
    totalAmount: 18500,
    insuranceAmt: 12950,
    patientAmt: 5550,
    discountAmt: 0,
    status: 'PAID',
    items: [
      { id: 'ii-11', invoiceId: 'inv-4', description: '재진진찰료', category: '진찰료', quantity: 1, unitPrice: 10000, totalPrice: 10000 },
      { id: 'ii-12', invoiceId: 'inv-4', description: '타이레놀 500mg 15정', category: '약제비', quantity: 15, unitPrice: 50, totalPrice: 750 },
      { id: 'ii-13', invoiceId: 'inv-4', description: '세티리진 10mg 5정', category: '약제비', quantity: 5, unitPrice: 95, totalPrice: 475 },
      { id: 'ii-14', invoiceId: 'inv-4', description: '인플루엔자 신속항원검사', category: '검사료', quantity: 1, unitPrice: 7275, totalPrice: 7275 },
    ],
    payments: [
      { id: 'pay-4', invoiceId: 'inv-4', amount: 5550, method: 'CARD', paidAt: '2026-05-28T10:25:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-5',
    invoiceNo: 'INV-202600005',
    patientId: 'patient-2',
    patientName: '김영희',
    totalAmount: 22800,
    insuranceAmt: 15960,
    patientAmt: 6840,
    discountAmt: 0,
    status: 'PAID',
    items: [
      { id: 'ii-15', invoiceId: 'inv-5', description: '초진진찰료', category: '진찰료', quantity: 1, unitPrice: 15000, totalPrice: 15000 },
      { id: 'ii-16', invoiceId: 'inv-5', description: '판토록정 40mg 14정', category: '약제비', quantity: 14, unitPrice: 200, totalPrice: 2800 },
      { id: 'ii-17', invoiceId: 'inv-5', description: '상복부 초음파', category: '검사료', quantity: 1, unitPrice: 5000, totalPrice: 5000 },
    ],
    payments: [
      { id: 'pay-5', invoiceId: 'inv-5', amount: 6840, method: 'CARD', paidAt: '2026-05-28T12:05:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-6',
    invoiceNo: 'INV-202600006',
    patientId: 'patient-7',
    patientName: '강준혁',
    totalAmount: 56000,
    insuranceAmt: 39200,
    patientAmt: 16800,
    discountAmt: 0,
    status: 'PAID',
    items: [
      { id: 'ii-18', invoiceId: 'inv-6', description: '재진진찰료', category: '진찰료', quantity: 1, unitPrice: 10000, totalPrice: 10000 },
      { id: 'ii-19', invoiceId: 'inv-6', description: '이부프로펜 400mg 20정', category: '약제비', quantity: 20, unitPrice: 80, totalPrice: 1600 },
      { id: 'ii-20', invoiceId: 'inv-6', description: '요추 MRI (3.0T)', category: '검사료', quantity: 1, unitPrice: 44400, totalPrice: 44400 },
    ],
    payments: [
      { id: 'pay-6', invoiceId: 'inv-6', amount: 16800, method: 'CARD', paidAt: '2026-05-26T10:00:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-7',
    invoiceNo: 'INV-202600007',
    patientId: 'patient-9',
    patientName: '임재원',
    totalAmount: 39880,
    insuranceAmt: 27916,
    patientAmt: 11964,
    discountAmt: 0,
    status: 'PENDING',
    items: [
      { id: 'ii-21', invoiceId: 'inv-7', description: '초진진찰료', category: '진찰료', quantity: 1, unitPrice: 15000, totalPrice: 15000 },
      { id: 'ii-22', invoiceId: 'inv-7', description: '흉부 X-ray', category: '검사료', quantity: 1, unitPrice: 11400, totalPrice: 11400 },
      { id: 'ii-23', invoiceId: 'inv-7', description: '혈액검사 (CBC, CRP)', category: '검사료', quantity: 1, unitPrice: 8080, totalPrice: 8080 },
      { id: 'ii-24', invoiceId: 'inv-7', description: '항생제(아목시실린/클라불라네이트) 21정', category: '약제비', quantity: 21, unitPrice: 280, totalPrice: 5880 },
    ],
    payments: [],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-8',
    invoiceNo: 'INV-202600008',
    patientId: 'patient-10',
    patientName: '송미경',
    totalAmount: 16520,
    insuranceAmt: 11564,
    patientAmt: 4956,
    discountAmt: 0,
    status: 'PAID',
    items: [
      { id: 'ii-25', invoiceId: 'inv-8', description: '초진진찰료', category: '진찰료', quantity: 1, unitPrice: 15000, totalPrice: 15000 },
      { id: 'ii-26', invoiceId: 'inv-8', description: '수마트립탄 50mg 6정', category: '약제비', quantity: 6, unitPrice: 253, totalPrice: 1520 },
    ],
    payments: [
      { id: 'pay-7', invoiceId: 'inv-8', amount: 4956, method: 'CARD', paidAt: '2026-05-22T12:00:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-9',
    invoiceNo: 'INV-202600009',
    patientId: 'patient-11',
    patientName: '오태양',
    totalAmount: 1250000,
    insuranceAmt: 875000,
    patientAmt: 375000,
    discountAmt: 0,
    status: 'PARTIAL',
    notes: '수술비 분납 진행 중',
    items: [
      { id: 'ii-27', invoiceId: 'inv-9', description: '충수돌기절제술 (복강경)', category: '처치료', quantity: 1, unitPrice: 900000, totalPrice: 900000 },
      { id: 'ii-28', invoiceId: 'inv-9', description: '마취료', category: '처치료', quantity: 1, unitPrice: 200000, totalPrice: 200000 },
      { id: 'ii-29', invoiceId: 'inv-9', description: '입원료 (1일)', category: '입원료', quantity: 1, unitPrice: 80000, totalPrice: 80000 },
      { id: 'ii-30', invoiceId: 'inv-9', description: '검사비 (혈액, X-ray)', category: '검사료', quantity: 1, unitPrice: 70000, totalPrice: 70000 },
    ],
    payments: [
      { id: 'pay-8', invoiceId: 'inv-9', amount: 200000, method: 'CARD', paidAt: '2026-05-20T22:00:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'inv-10',
    invoiceNo: 'INV-202600010',
    patientId: 'patient-4',
    patientName: '이미래',
    totalAmount: 20730,
    insuranceAmt: 14511,
    patientAmt: 6219,
    discountAmt: 0,
    status: 'PAID',
    items: [
      { id: 'ii-31', invoiceId: 'inv-10', description: '초진진찰료', category: '진찰료', quantity: 1, unitPrice: 15000, totalPrice: 15000 },
      { id: 'ii-32', invoiceId: 'inv-10', description: 'A군 연쇄구균 신속항원검사', category: '검사료', quantity: 1, unitPrice: 2100, totalPrice: 2100 },
      { id: 'ii-33', invoiceId: 'inv-10', description: '아목시실린 250mg 21캡슐', category: '약제비', quantity: 21, unitPrice: 60, totalPrice: 1260 },
      { id: 'ii-34', invoiceId: 'inv-10', description: '타이레놀 500mg 10정', category: '약제비', quantity: 10, unitPrice: 37, totalPrice: 370 },
    ],
    payments: [
      { id: 'pay-9', invoiceId: 'inv-10', amount: 6219, method: 'CASH', paidAt: '2026-05-10T16:15:00.000Z' },
    ],
    createdAt: now(),
    updatedAt: now(),
  },
];

// ── Refresh Tokens ────────────────────────────────────────────────
export const refreshTokens: { token: string; userId: string; expiresAt: Date }[] = [];

// ── JSON Snapshot Persistence ─────────────────────────────────────
const SNAPSHOT_DIR  = path.join(__dirname, '../../data');
const SNAPSHOT_FILE = path.join(SNAPSHOT_DIR, 'snapshot.json');

function saveSnapshot() {
  try {
    fs.mkdirSync(SNAPSHOT_DIR, { recursive: true });
    fs.writeFileSync(
      SNAPSHOT_FILE,
      JSON.stringify({
        counters: { _patientCnt, _appointmentCnt, _recordCnt, _prescriptionCnt, _invoiceCnt },
        patients,
        appointments,
        medicalRecords,
        recordDiagnoses,
        labResults,
        medications,
        prescriptions,
        invoices,
      }, null, 2),
    );
  } catch { /* 저장 실패 시 무시 */ }
}

function loadSnapshot() {
  try {
    if (!fs.existsSync(SNAPSHOT_FILE)) return;
    const raw = JSON.parse(fs.readFileSync(SNAPSHOT_FILE, 'utf-8'));

    if (raw.counters) {
      _patientCnt      = raw.counters._patientCnt;
      _appointmentCnt  = raw.counters._appointmentCnt;
      _recordCnt       = raw.counters._recordCnt;
      _prescriptionCnt = raw.counters._prescriptionCnt;
      _invoiceCnt      = raw.counters._invoiceCnt;
    }
    const restore = <T>(arr: T[], saved: T[] | undefined) => {
      if (saved?.length) arr.splice(0, arr.length, ...saved);
    };
    restore(patients,        raw.patients);
    restore(appointments,    raw.appointments);
    restore(medicalRecords,  raw.medicalRecords);
    restore(recordDiagnoses, raw.recordDiagnoses);
    restore(labResults,      raw.labResults);
    restore(medications,     raw.medications);
    restore(prescriptions,   raw.prescriptions);
    restore(invoices,        raw.invoices);
    console.log(`[mockDb] 스냅샷 복원: ${SNAPSHOT_FILE}`);
  } catch (e) {
    console.warn('[mockDb] 스냅샷 로드 실패, 기본 데이터 사용:', e);
  }
}

// 시작 시 복원
loadSnapshot();

// 30초마다 자동 저장
const _saveInterval = setInterval(saveSnapshot, 30_000);
_saveInterval.unref(); // 이 타이머가 프로세스 종료를 막지 않도록

// 프로세스 종료 시 최종 저장
process.on('exit',    saveSnapshot);
process.on('SIGINT',  () => { saveSnapshot(); process.exit(); });
process.on('SIGTERM', () => { saveSnapshot(); process.exit(); });

// 서비스에서 쓰기 작업 후 즉시 저장할 때 사용
export { saveSnapshot };
